### ISSUE TITLE
MacVim font editing?

### ISSUE THREAD

**Issue by ylluminate** [SebastianMuskalla/ModelessVim#2]
Any thoughts on how to make this compatible with MacVim? It kinda seems to work, but it seems to be missing the header and footer fonts, eg:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/8Luld8W9/2972259b-3d72-4040-b1bc-5f1a20baf67b.jpg?v=33a6f63314e0ba05d6bf0b9408f38c59)

**Comment by SebastianMuskalla** [comment]
Hello,

The problem is probably that by default, my config files use Nerd Font symbols,
see the following section of the README: https://github.com/SebastianMuskalla/ModelessVim#nerd-font

You have two options
1. Install a Nerd Font and use it in your terminal
2. Edit `modeless.vimrc`  so that the `_ascii` versions of the config files are used. If you do that, it will look not quite as nice, but it will work without changing the font.

If this doesn't help, feel free to open another issue.

**Comment by luilver** [comment]
Actually option 2 works like a charm. You could see #4 (last comment within Dockerfile) or the picture below for a reference.

By the way this is how it looks like in macOS: Beautiful!

![WhatsApp Image 2024-01-18 at 1 22 07 AM](https://github.com/SebastianMuskalla/ModelessVim/assets/681020/a622f2b4-63f7-4248-9ed8-473889035bef)

**Comment by ylluminate** [comment]
Fwiw, the bottom status line issue is resolved in MacVim, but the top line is missing. Not a big deal as I don't plan to really use MacVim much - more of a curiosity for me. It would be interesting to see how this might be resolved to make MacVim play nice together with your config.
