### ISSUE TITLE
Hello from another similar project!

### ISSUE THREAD

**Issue by tombh** [SebastianMuskalla/ModelessVim#3]
I made a plugin for this too! https://github.com/tombh/novim-mode I've only just seen your project from the Hacker News thread: https://news.ycombinator.com/item?id=39008533 I'm going to pore over your code and see where we can share ideas.

So glad to see there are other people out there with a similar view on Vim.

**Comment by SebastianMuskalla** [comment]
Thanks to your comment here, I realized that the thread on Hacker News exists. Pretty cool that something that I did a few years ago for fun now has sparked a discussion with 350+ comments ... even if not all of them are positive 😄 

I have to admit that I currently barely use vim at all.
If you find something useful in my config files, feel free to use it!

**Comment by ylluminate** [comment]
Being an `emacs` user and just having the ability to have a more sane `vi` option if/when need arises on servers and otherwise is nice. I have hated `vi` for about 25 years now and your work @SebastianMuskalla and @tombh are a real blessing to have in the holster. (Not that I don't know commands already sufficiently to use vi[m] if needed, but I dislike it and have resisted learning more than very rudimentary functionality.) 😋

**Comment by tombh** [comment]
Exactly! It's been decades for me too, and while I definitely know enough `vi` commands to get by, it's just not my thing. There are so many other nice things about, well `nvim` for me, that are great. I'm a senior software engineer and am perfectly productive with just conventional keybindings 💪
